"""initial schema

Revision ID: 6e81858e3cb2
Revises: 
Create Date: 2026-03-18 00:24:15.510637
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '6e81858e3cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('github_username')
    )
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_repo_url', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('latest_version', sa.String(length=50), nullable=True),
    sa.Column('categories', ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', ARRAY(sa.String()), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=True),
    sa.Column('danger_rating', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_command_name'), 'commands', ['command_name'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'author_id', name='uq_review_per_author')
    )
    op.create_table('security_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('ai_review_summary', sa.Text(), nullable=True),
    sa.Column('ai_danger_score', sa.Integer(), nullable=True),
    sa.Column('ai_concerns', ARRAY(sa.String()), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=20), nullable=True),
    sa.Column('overall_danger_rating', sa.Integer(), nullable=True),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('github_repo_url', sa.String(length=512), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('git_tag', sa.String(length=100), nullable=True),
    sa.Column('git_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('danger_rating', sa.Integer(), nullable=True),
    sa.Column('security_report_id', sa.Integer(), nullable=True),
    sa.Column('min_jarvis_version', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['security_report_id'], ['security_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'version', name='uq_command_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_versions')
    op.drop_table('submissions')
    op.drop_table('security_reports')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_commands_command_name'), table_name='commands')
    op.drop_table('commands')
    op.drop_table('authors')
    # ### end Alembic commands ###
